title: "Blog de Alejandro"
description: "Un espacio para aprender sobre desarrollo web e inteligencia artificial"
theme: jekyll-theme-cayman

# Activa los plugins m√≠nimos
plugins:
  - jekyll-feed

markdown: kramdown
